# Generated by Django 4.1.3 on 2022-12-03 00:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="proyect",
            options={
                "ordering": ["-created"],
                "verbose_name": "proyecto",
                "verbose_name_plural": "proyectos",
            },
        ),
        migrations.RemoveField(
            model_name="proyect",
            name="create",
        ),
        migrations.AddField(
            model_name="proyect",
            name="URLField",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="proyect",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Fecha de Creación",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="proyect",
            name="description",
            field=models.TextField(verbose_name="Descripción"),
        ),
        migrations.AlterField(
            model_name="proyect",
            name="image",
            field=models.ImageField(upload_to="", verbose_name="Imagen"),
        ),
        migrations.AlterField(
            model_name="proyect",
            name="title",
            field=models.CharField(max_length=200, verbose_name="Título"),
        ),
        migrations.AlterField(
            model_name="proyect",
            name="update",
            field=models.DateField(
                auto_now=True, verbose_name="Fecha de Actualizacion"
            ),
        ),
    ]
